### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by fooooooooooooooo** [fooooooooooooooo/upc#8]
```
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'error_notifier'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'error_notifier'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 3 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'error_notifier'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 5 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: Class me.shedaniel.errornotifier.fabric.ErrorNotifierFabric cannot be cast to net.fabricmc.loader.api.entrypoint.PreLaunchEntrypoint!
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:63)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 6 more
```

It seems to be coming from rei, but I cant find any information on why

**Comment by MSandro** [comment]
I am not a good java developer so I have no idea what the problem could be. 
not sure why but I was able to build it without any problem.
[upc-0.0.3.jar.zip](https://github.com/fooooooooooooooo/upc/files/11545988/upc-0.0.3.jar.zip)
remove the .zip extension from the file name and feel free to upload it to CurseForge if this would be an acceptable workaround for you.

**Comment by MSandro** [comment]
I should mention that this build was made bevore your last two commits:
![image](https://github.com/fooooooooooooooo/upc/assets/10937159/2ea8e67a-0e01-432f-b87f-d841880a76ff)
I will pull it and let you know if I am able to build your current state.

**Comment by MSandro** [comment]
I am not able to build the current state of your 1.18.2 Branch, sorry.
